### ISSUE TITLE
Clustering markers on the map via vuejs component

### ISSUE THREAD

**Issue by jdseen** [geospoc/v-mapbox#1045]
Any idea how can I transform the example here https://docs.mapbox.com/mapbox-gl-js/example/cluster/ to the format that works with Vuejs component?

**Comment by vinayakkulkarni** [comment]
@jdseen:

- [x] Source code – https://github.com/vinayakkulkarni/cluster
- [x] Demo – https://vinayakkulkarni.github.io/cluster/
