### ISSUE TITLE
missing required property "version"

### ISSUE THREAD

**Issue by ibmsoft** [geospoc/v-mapbox#114]
![image](https://user-images.githubusercontent.com/26042/92893299-24c7ff00-f44c-11ea-81d0-338b8c33760e.png)

```
<template>
  <MglMap :accessToken="accessToken" version="12" :mapStyle="mapStyle" />
</template>

<script>
import "mapbox-gl/dist/mapbox-gl.css";
import Mapbox from "mapbox-gl";
import { MglMap } from "v-mapbox";

export default {
  components: {
    MglMap,
  },
  data() {
    return {
      accessToken:
        "xxx", // your access token. Needed if you using Mapbox maps
      mapStyle: {}, // your map style
    };
  },

  created() {
    // We need to set mapbox-gl library here in order to use it in template
    this.mapbox = Mapbox;
  },
};
</script>
```

**Comment by Kyle123** [comment]
You're passing an empty object. to the `mapStyle` property - this should be a `String` or an object that conforms to the Mapbox Style Specification. The errors you are getting aren't errors for the map version, they're validation errors of the style object you've passed, the object should be in the format:
```
{
    "version": 8,
    "name": "Mapbox Streets",
    "sprite": "mapbox://sprites/mapbox/streets-v8",
    "glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
    "sources": {...},
    "layers": [...]
}
```
[Documentation](https://docs.mapbox.com/mapbox-gl-js/style-spec/root/)

I suspect that you probably want to use the string format

**Comment by ibmsoft** [comment]
thanks,
