### ISSUE TITLE
The setup binding property "templateRefs" is already declared  (vuejs2 legacy version)

### ISSUE THREAD

**Issue by kor3k** [geospoc/v-mapbox#1293]
hello, i can't get it working. 

i am using

`"v-mapbox": "^1.11.2"`

like this

```vue
<template>
  <MglMap
      :access-token="accessToken"
      :map-style.sync="style"
  ></MglMap>
</template>

<script>
import 'mapbox-gl/dist/mapbox-gl.css'
import 'v-mapbox/dist/v-mapbox.css'
import Mapbox from 'mapbox-gl'
import VMap from 'v-mapbox'
Vue.use(VMap)
</script>
```

and i got this error

```
[Vue warn]: The setup binding property "templateRefs" is already declared.

found in

---> <MglMap>
```

any idea what i am doing wrong?

**Comment by dirksierd** [comment]
Hi @kor3k, I stumbled upon this as well. On my end this was related to using Vue 2.7, which has the composition-api features of Vue 3 backported. Rolling back to Vue 2.6 fixed the issue for me.

**Comment by kor3k** [comment]
@dirksierd hello. thank you for hinting that. unfortunately that rollback to vue 2.6 is a not an option for me.. but it seems like the only solution, so i close this.
