### ISSUE TITLE
package is empty

### ISSUE THREAD

**Issue by diegogarciar** [geospoc/v-mapbox#130]
Hello again, I was going crazy as I'm installing the package via npm i v-mapbox but its saying that the dependency was not found. 1 hour later, I realize that the package is actually empty

<img width="407" alt="Screen Shot 2020-09-24 at 18 32 01" src="https://user-images.githubusercontent.com/17276155/94213582-687f2780-fe94-11ea-9329-a9cf8883562c.png">

**Comment by vinayakkulkarni** [comment]
Hmm. weird, I'll look into it.

If you look at the workflow, CI/CD has built the package and published it successfully

https://github.com/geospoc/v-mapbox/runs/1127972566

**Comment by vinayakkulkarni** [comment]
unable to reproduce this. I was able to view the `dist` directory in the `node_modules/v-mapbox/`
