### ISSUE TITLE
max-bounds can be array or object

### ISSUE THREAD

**Issue by vchrisb** [geospoc/v-mapbox#137]
The [max-bounds](https://v-mapbox.netlify.app/api/#props) property can be either array or LngLatBoundsLike object.
Currently only validated against arrray:
https://github.com/geospoc/v-mapbox/blob/main/src/components/map/options.js#L96

simple workaround:
`:max-bounds="maxBounds.toArray()`

**Comment by vinayakkulkarni** [comment]
- [x] fixed in #138
