### ISSUE TITLE
Release build not showing map

### ISSUE THREAD

**Issue by vvavepacket** [geospoc/v-mapbox#181]
Hello since the [ticket ](https://github.com/geospoc/v-mapbox/issues/167)has been closed and no longer be opened. Below is the bug and some root cause analysis

I can confirm that release build is not working. I deployed it to my local web server and it doesn't work. I inspected the layout and it seems that the css files are not being loaded properly, as I can see the classes are not attached to the mapbox divs.

I added the css manually in the inspector and here is before and after

Before - its blank
![image](https://user-images.githubusercontent.com/8295642/97650990-60854b00-1a31-11eb-99bf-5402c6734518.png)

After - map appears
![image](https://user-images.githubusercontent.com/8295642/97651001-65e29580-1a31-11eb-8e10-f45f22c350a4.png)

I checked the build css files that was generated and the style mgl-map-wrapper can't be found, hence not rendering...
![image](https://user-images.githubusercontent.com/8295642/97651013-6aa74980-1a31-11eb-9615-8a26ba02f07b.png)

Can you please advise? I tried building the native mapbox gl js release version and I didn't face the issue. For some reason in this library during the build process, the css is not properly attached or generated on the dist build

**Comment by vvavepacket** [comment]
Welp, I just copied this css coming from this library to my main vue js file



```
.mgl-map-wrapper {
  height: 100%;
  position: relative;
  width: 100%;
}
.mgl-map-wrapper .mapboxgl-map {
  height: 100%;
  left: 0;
  position: absolute;
  top: 0;
  width: 100%;
}
```

and it worked.. Why was this not being autocopied when building my release? Other libraries/dependencies css are being copied over but not this library...

cc: @woshikie

**Comment by woshikie** [comment]
Let me copy over from the other ticket in case @vinayakkulkarni missed it

I have updated my repo with the latest package and this is the output from my npm run build.

dist.zip

You can see for yourself that the map is not showing. It is showing, however, on debug builds, which we can see on CodeSandbox or npn run serve

If you don't have a development web server to run the files, you can use python as a web server.
Assuming you are using python 3 and you extracted the zip file to your current working directory:
python -m http.server --directory dist
You should be able to reach your python web server on http://localhost:8000 (by default)

Edit: not opening a new issue as we can simply reopen this one

**Comment by woshikie** [comment]
It seems that `"sideEffect"` in `package.json` controls if the css will be excluded.
I have made a pull request ( #182 ) to fix this.
More information about `"sideEffect"` in vuejs/vue-cli#4832 

I also see that @vinayakkulkarni has suggested another alternate fix in woshikie/mapbox-bug-demo#1

I think #182 fix is better, imo.

**Comment by vinayakkulkarni** [comment]
@woshikie & @vvavepacket: Kindly refer to this PR - https://github.com/woshikie/mapbox-bug-demo/pull/1, as this is a configuration issue but not an issue with `v-mapbox` per se

**Comment by woshikie** [comment]
One of the commenters in the vue-cli issue quoted:

> https://vue-loader.vuejs.org/guide/#manual-setup
> Scroll to the bottom.
> 
> > If you are developing a library or in a monorepo, please be aware that CSS imports **are side effects**. Make sure to **remove** `"sideEffects": false` in the `package.json`, otherwise CSS chunks will be dropped by webpack in production builds.

I believe we should reopen #182 or @vinayakkulkarni could author a similar patch.

**Comment by vinayakkulkarni** [comment]
That's actually an issue with your vue repo which bundles the package using `vue-cli-service` right? not with the library per se. The library is built using rollup & not webpack anyways

**Comment by woshikie** [comment]
This is the artifact built on this repo's main branch

[package.zip](https://github.com/geospoc/v-mapbox/files/5463727/package.zip)

We can see that in its `package.json` there is a line describing `"sideEffects": false`.
This line here stopped the bundle process from including the `css` files

**Comment by whatcould** [comment]
This was an issue for me, importing the js via webpack. Not sure what the solution is internally, but it's still a problem.

Worked around it by manually adding the `.mgl-map-wrapper` css above into my project.
