### ISSUE TITLE
Custom Marker

### ISSUE THREAD

**Issue by vvavepacket** [geospoc/v-mapbox#214]
Hello, how does one create a custom marker (like a custom icon) using your library? How can we do it the reactive vue way?

I can do it in plain vanilla JS like what is specified [here](https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/), but I was curious what strategy would you recommend to support custom markers with `v-mapbox`?

**Comment by ConnorOnTheWeb** [comment]
Did you ever figure it out?

Looking to use custom icons with v-mapbox markers right now

**Comment by vinayakkulkarni** [comment]
You have a slot called as `marker` within the `<MglMarker><svg slot="marker">......</svg></MglMarker>`  for adding custom marker(s)

**Comment by timgoeller** [comment]
How does this work with the new version?
