### ISSUE TITLE
Consider moving to a fork on Mapbox GL JS 1.xx

### ISSUE THREAD

**Issue by ajinkya** [geospoc/v-mapbox#223]
Can we shift to start using a fork instead of the main mapbox gl js library, now that the latter is no longer open source ?

There is already a request for bindings on the [maps-gl/maps-gl#18](https://github.com/maps-gl/maps-gl/issues/18)

**Comment by vinayakkulkarni** [comment]
Yes we can.

**Comment by ajinkya** [comment]
As per the latest updates on here [maps-gl/maps-gl/#21#issuecomment-741997120](https://github.com/maps-gl/maps-gl/issues/21#issuecomment-741997120)

Please also consider using this [https://github.com/MapLibre/maplibre-gl-js](https://github.com/MapLibre/maplibre-gl-js)

**Comment by zakjan** [comment]
Possibly unpopular opinion, but it would be great to keep compatibility with both MapLibre and Mapbox. The library can be already passed with mapboxGl param.

**Comment by vinayakkulkarni** [comment]
Migrated to `maplibre-gl` in Release [`v4.x`](https://github.com/geospoc/v-mapbox/pull/1390)
