### ISSUE TITLE
Default marker offset should be [0, -14], not [0, 0]

### ISSUE THREAD

**Issue by lights0123** [geospoc/v-mapbox#309]
By default, [Mapbox creates](https://github.com/mapbox/mapbox-gl-js/blob/ef7b2cb243f983fef7482502021e26bda93896e2/test/unit/ui/marker.test.js#L20) markers with an offset of `[0, -14`]. However, this library makes it `[0, 0]`:

https://github.com/geospoc/v-mapbox/blob/f113c84fce01f5a0b2d204c00a32166a524da4f1/src/components/UI/Marker.vue#L45

This causes markers to not actually show the correct location by default.

**Comment by Maker-Mark** [comment]
this looks like a good first issue. I'd be happy to knock that out.

**Comment by vinayakkulkarni** [comment]
> this looks like a good first issue. I'd be happy to knock that out.

Feel free to open a PR @Maker-Mark. Contributions welcome 🎊

**Comment by vinayakkulkarni** [comment]
Should be fixed in https://github.com/geospoc/v-mapbox/commit/009ecf6788607730c6359e1df4443ad6c497b7fc
