### ISSUE TITLE
Streets displayed with dots - help wanted

### ISSUE THREAD

**Issue by mikhi** [geospoc/v-mapbox#332]
Hi,
I'm looking for some help / guidance. 
Do you have any idea why the streets are rendered using dots?

![image](https://user-images.githubusercontent.com/1406293/113846603-51a08280-979f-11eb-8b38-4744792d4632.png)

The expected display is something like this:

![image](https://user-images.githubusercontent.com/1406293/113846989-b360ec80-979f-11eb-8162-fd4a574e4778.png)

Thanks,
Mihai

**Comment by jovicon** [comment]
Do you have this code in a repo to replicate the issue?

**Comment by vinayakkulkarni** [comment]
If you store the map in store or as a reactive variable, you'll have this issue.

Simple solution is to store the map variable in a non-reactive variable:

https://codesandbox.io/s/k1l1n

**Comment by vinayakkulkarni** [comment]
If you store it as a reactive variable, Vue breaks it, you have to store it as a readonly or shallowReadonly variable or a non-reactive variable.
