### ISSUE TITLE
Compatibility with Node 12/14?

### ISSUE THREAD

**Issue by allanlewis** [geospoc/v-mapbox#586]
I am using Node 12 LTS, which is supported until next year, and I get this message when installing this package:

```
error v-mapbox@1.9.0: The engine "node" is incompatible with this module. Expected version ">=16.5.0". Got "12.22.7"
```

Would it be possible to add support for Node 12? Or at least Node 14? Upgrading my app to Node 16 is difficult due to other dependencies.

**Comment by allanlewis** [comment]
I'm probably going to upgrade my app to Node 14 soon, so compatibility with that would be enough for me. Is there a reason why this package can't support Node 14?

**Comment by vinayakkulkarni** [comment]
I have removed the `engines` from `package.json` in version 3.x, should be able to support any Node version. but I recommend always update to current node version as per [.nvmrc](https://github.com/geospoc/v-mapbox/blob/main/.nvmrc)
