### ISSUE TITLE
add vue 3 support using composition api

### ISSUE THREAD

**Issue by vinayakkulkarni** [geospoc/v-mapbox#60]
... and possibly use TypeScript :)

**Comment by vinayakkulkarni** [comment]
- reference: https://github.com/soal/vue-mapbox/issues/111#issuecomment-662985533

**Comment by FrankySnow** [comment]
Hello !
Are you making any progress on this side ? I don't see any commit on the `refactor/vue-3` branch since november 2020.
Is the library already compatible with Vue 3 ?
Thanks !

**Comment by FrankySnow** [comment]
@vinayakkulkarni bump on this

**Comment by iBobik** [comment]
My client has a will to contribute few hundreds Euros if there will be crowdfunding on Vue 3 support.

**Comment by vinayakkulkarni** [comment]
> My client has a will to contribute few hundreds Euros if there will be crowdfunding on Vue 3 support.

That is really generous @iBobik, and I really appreciate this but I have been working & have pushed Vue 3 support in v3.x.
You can test it out by cloning [this repo](https://github.com/geoql/expenses) and testing it out yourself :)

Closing this as I have to work on the documentation bit so that we can have v3.1.x w/ correct guidance for users using Vue 3/ Nuxt 3
