### ISSUE TITLE
Trouble getting started with Nuxt

### ISSUE THREAD

**Issue by ConnorOnTheWeb** [geospoc/v-mapbox#702]
Fresh install, using nuxt with vuetify. Access token and mapStyle are set.

Tried this from #328 

> _/plugins/mapbox.js_
> 
> ```
> /* eslint-disable import/no-extraneous-dependencies */
> import Vue from 'vue';
> import {
>   MglMap,
>   MglGeolocateControl,
>   MglGeojsonLayer,
>   MglMarker,
> } from 'v-mapbox';
> 
> Vue.component('MglMap', MglMap);
> Vue.component('MglGeolocateControl', MglGeolocateControl);
> Vue.component('MglMarker', MglMarker);
> Vue.component('MglGeojsonLayer', MglGeojsonLayer);
> ```
> 
> _/nuxt.config.js_ `plugins: [ { src: '~/plugins/mapbox', mode: 'client' }, ],`

Added stylesheets on the page and globally

>css: [
>    'node_modules/mapbox-gl/dist/mapbox-gl.css', 'node_modules/v-mapbox/dist/v-mapbox.css'
>  ],

Not working for me. I'm getting 2 errors:

>[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside \<p>, or missing \<tbody>. Bailing hydration and performing full client-side render.

>v-mapbox.esm.js?5e6e:1291 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'container')

Also tried the example here: [Base map](https://v-mapbox.netlify.app/guide/basemap.html#adding-map-component)

Error I get is this

>window is not defined

Not sure where to go or what to try from here.

**Comment by vinayakkulkarni** [comment]
You have to wrap the <mgl-map> component in the [`<client-only>`](https://nuxtjs.org/docs/features/nuxt-components/#the-client-only-component) tag within the template.

Also, try disabling ssr in `nuxt.config.ts`: 

```ts
export default {
  # ....
   ssr: false,
  # ....
}

**Comment by ConnorOnTheWeb** [comment]
Tried both, it's not having it. No changes. This is what I've got on the page.

```
<template>
  <v-container fluid pa-0>
    <div>
      <client-only>
        <MglMap :accessToken="accessToken" :mapStyle="mapStyle" />
      </client-only>

    </div>
  </v-container>
</template>

<script>
import 'mapbox-gl/dist/mapbox-gl.css'
import 'v-mapbox/dist/v-mapbox.css';
export default {
  data: () => ({
    accessToken: ACCESS_TOKEN,
    mapStyle: 'mapbox://styles/mapbox/streets-v11'
  })
}
</script>
```

Noticed another error

`DevTools failed to load source map: Could not load content for http://localhost:3000/_nuxt/vendors/pages/map/v-mapbox.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by vinayakkulkarni** [comment]
https://codesandbox.io/s/v-mapbox-with-nuxt-lbrt6?file=/pages/index.vue

^^ I just did a repro here, can you verify/validate it with your own nuxt app ?

**Comment by ConnorOnTheWeb** [comment]
Not working for me. Same two errors: "Cannot read properties of undefined (reading 'container')" and "Could not load content". I'm using npm, instead of yarn, is it possible that's an issue?

Also, I need the site to be Server Side Rendered, just the map to be client only. Trying to figure out how to get it working that way.

**Comment by ConnorOnTheWeb** [comment]
Got it! (well, almost)

It works in SSR with Nuxt 2 importing the Nuxt Composition API, that was the missing link.

Problem now is that I decided to make the switch to Nuxt Bridge (if possible) and now it doesn't work.

**Comment by vinayakkulkarni** [comment]
@ConnorOnTheWeb: I'm completely refactoring the code to with Vue 3 as base & support for Vue 2 via [`vue-demi`](https://github.com/vueuse/vue-demi), currently it lies in the [directory](https://github.com/geoql/expenses/tree/dev/lib/v-mapbox) of another repo, but I am making progress (mostly over the weekend(s) & later in the day off work) surely but (unfortunately) slowly. I still have to research a bit on how to support it for SSR but CSR is already supported out-of-the-box

**Comment by ConnorOnTheWeb** [comment]
@vinayakkulkarni I appreciate your work here. I've made v-mapbox load in a satisfactory way, with SSR using Nuxt 2 and the Nuxt Composition API, now just a couple more details continued in the next thread #713
